server:
 port: 8321

management:
 tracing:
  sampling:
   probability: 1.0
      
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: supply_service
 datasource:
  driver-class-name: org.postgresql.Driver 
  url: jdbc:postgresql://localhost:4321/product
  username: admin
  password: admin
 jpa:
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
 
        
 security:
  oauth2:
   resourceserver:
    jwt:
     jwk-set-uri: http://localhost:8920/auth/realms/Song_control/protocol/openid-connect/certs
 kafka:
  bootstrap-servers: localhost:9092
  producer:
   key-serializer: org.apache.kafka.common.serialization.StringSerializer
   value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
   group-id: group_id
   auto-offset-reset: earliest
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   value-deserializer: org.apache.kafka.common.serialization.StringDeserializer